name: mypymeapp
channels: 
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - matplotlib=3.10.3
  - mysqlclient
  - numpy>=1.24,<3
  - pandas=2.3.1
  - werkzeug=3.1.3
  - pip
  - pip: 
      - opencv-python==4.5.3.56
      - mysql_connector_repackaged==0.3.1
      - docxtpl==0.20.1  
      - pyqt6-sip==13.10.0  
      - pyqt6==6.9.1