CREATE TABLE BRANCHES (
	Branch_ID INT PRIMARY KEY AUTO_INCREMENT, -- AUTO_INCREMENT CHO MYSQL
	Branch_name NVARCHAR(255),
	Branch_address NVARCHAR(255),
	Branch_phone_number CHAR(15) CHECK(REGEXP_LIKE(Branch_phone_number,"^[0-9]{10,15}$")),
	Create_at DATETIME
);
CREATE TABLE REVENUE (
	Revenue_ID INT PRIMARY KEY AUTO_INCREMENT, -- AUTO_INCREMENT CHO MYSQL
	Revenue_date DATE,
	Amount DECIMAL(15, 2),
	Create_at DATETIME,
	Branch_ID INT
-- 	CONSTRAINT FK_BRANCH_REVENUE FOREIGN KEY (BRANCH_ID) REFERENCES BRANCHES(BRANCH_ID)
-- (CÓ AUTO_INCREMENT VÌ MYSQL KO HỖ TRỢ 'IDENTITY' VÀ CHECK'CONSTRAINT')
);
CREATE TABLE EMPLOYER(
	Employer_ID INT PRIMARY KEY AUTO_INCREMENT, -- AUTO_INCREMENT CHO MYSQL
	Employer_name NVARCHAR(255),
	DOB DATE,
	Create_at DATETIME,
	Employer_password Varchar(255)
);
CREATE TABLE ENTERPRISE(
	ENTERPRISE_ID INT PRIMARY KEY AUTO_INCREMENT, -- AUTO_INCREMENT CHO MYSQL
	ENTERPRISE_NAME NVARCHAR(255),
    ENTERPRISE_FOUNDER NVARCHAR(255),
    ADDRESS TEXT,
    ENTERPRISE_PHONE_NUMBER VARCHAR(255),
    BUSINESS_TYPE VARCHAR(255),
    INDUSTRY NVARCHAR(255)
);
CREATE TABLE PRODUCT(
		PRODUCT_ID INT PRIMARY KEY AUTO_INCREMENT, -- AUTO_INCREMENT CHO MYSQL
        PRODUCT_NAME NVARCHAR(255),
        PRICE DECIMAL(15,2),
        AMOUNT INT
);
CREATE TABLE PRODUCT_SALES (
	SALE_ID VARCHAR(255),
    PRODUCT_ID INT,
    BRANCH_ID INT,
    SALE_DATE DATE,
    QUANTITY_SOLD INT,
    SALE_AMOUNT DECIMAL(15,2)
);
Create table Login_User(
User_ID INT PRIMARY KEY AUTO_INCREMENT,
User_Name NVARCHAR(30),
user_password VARCHAR(255),
user_gmail VARCHAR(255)
);
