CREATE TABLE BRANCHES (
	Branch_ID INT PRIMARY KEY IDENTITY(1, 1), --AUTO_INCREMENT CHO MYSQL--
	Branch_name NVARCHAR(255),
	Branch_address NVARCHAR(255),
	Branch_phone_number CHAR(15)  CHECK (Branch_phone_number LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]%' AND LEN(BRANCH_PHONE_NUMBER) BETWEEN 10 AND 15),
	Create_at DATETIME
)
CREATE TABLE REVENUE (
	Revenue_ID INT PRIMARY KEY IDENTITY(1, 1), --AUTO_INCREMENT CHO MYSQL--
	Revenue_date DATE,
	Amount DECIMAL(15, 2),
	Create_at DATETIME,
	Branch_ID INT
	CONSTRAINT FK_BRANCH_REVENUE FOREIGN KEY (BRANCH_ID) REFERENCES BRANCHES(BRANCH_ID)
)
CREATE TABLE EMPLOYER(
	Employer_ID INT PRIMARY KEY IDENTITY(1, 1), --AUTO_INCREMENT CHO MYSQL--
	Employer_name NVARCHAR(255),
	DOB DATE,
	Create_at DATETIME,
	Employer_password Varchar(255)
)
