# Form implementation generated from reading ui file 'D:\PYTHON\loginNew1.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(743, 505)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(9, 9, 301, 451))
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setGeometry(QtCore.QRect(0, 0, 301, 451))
        self.label.setObjectName("label")
        self.widget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(315, 9, 421, 451))
        self.widget_2.setObjectName("widget_2")
        self.usernameLineEdit = QtWidgets.QLineEdit(parent=self.widget_2)
        self.usernameLineEdit.setGeometry(QtCore.QRect(70, 120, 271, 21))
        self.usernameLineEdit.setObjectName("usernameLineEdit")
        self.passLineEdit = QtWidgets.QLineEdit(parent=self.widget_2)
        self.passLineEdit.setGeometry(QtCore.QRect(70, 190, 271, 21))
        self.passLineEdit.setObjectName("passLineEdit")
        self.usernameLabel = QtWidgets.QLabel(parent=self.widget_2)
        self.usernameLabel.setGeometry(QtCore.QRect(70, 100, 100, 16))
        self.usernameLabel.setObjectName("usernameLabel")
        self.passLabel = QtWidgets.QLabel(parent=self.widget_2)
        self.passLabel.setGeometry(QtCore.QRect(70, 170, 100, 16))
        self.passLabel.setObjectName("passLabel")
        self.login_btn = QtWidgets.QPushButton(parent=self.widget_2)
        self.login_btn.setGeometry(QtCore.QRect(160 , 230, 91, 31))
        self.login_btn.setObjectName("login_btn")
        self.register_btn = QtWidgets.QPushButton(parent=self.widget_2)
        self.register_btn.setGeometry(QtCore.QRect(70, 270, 271, 31))
        self.register_btn.setObjectName("register_btn")
        self.title_header = QtWidgets.QLabel(parent=self.widget_2)
        self.title_header.setGeometry(QtCore.QRect(78, 20, 261, 61))
        self.title_header.setIndent(0)
        self.title_header.setObjectName("title_header")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 743, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.usernameLabel.setText(_translate("MainWindow", "TextLabel"))
        self.passLabel.setText(_translate("MainWindow", "TextLabel"))
        self.login_btn.setText(_translate("MainWindow", "PushButton"))
        self.register_btn.setText(_translate("MainWindow", "PushButton"))
        self.title_header.setText(_translate("MainWindow", "TextLabel"))
